-- =====================================================================
-- 05_GOVERNANCE_RBAC_RAP.SQL — RBAC, ROW ACCESS POLICIES, MASKING & AUDIT
-- Snowflake CoCo Hackathon Track 5
-- =====================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE ONTO_HACKATHON;
USE SCHEMA GOV;

-- 1. DEFINE ROLES
CREATE ROLE IF NOT EXISTS ONTO_PLANNER COMMENT = 'Supply Chain Demand & Inventory Planner';
CREATE ROLE IF NOT EXISTS ONTO_PROCUREMENT COMMENT = 'Direct Procurement Lead with Cost Authority';
CREATE ROLE IF NOT EXISTS ONTO_LOGISTICS COMMENT = 'Logistics & Outbound Transportation Admin';
CREATE ROLE IF NOT EXISTS ONTO_JUDGE COMMENT = 'Hackathon Evaluation Lead (Full Inspection Access)';

-- Grant Roles to current user for testing
GRANT ROLE ONTO_PLANNER TO USER CURRENT_USER();
GRANT ROLE ONTO_PROCUREMENT TO USER CURRENT_USER();
GRANT ROLE ONTO_LOGISTICS TO USER CURRENT_USER();
GRANT ROLE ONTO_JUDGE TO USER CURRENT_USER();

-- Warehouse Grants
GRANT USAGE ON WAREHOUSE ONTO_WH TO ROLE ONTO_PLANNER;
GRANT USAGE ON WAREHOUSE ONTO_WH TO ROLE ONTO_PROCUREMENT;
GRANT USAGE ON WAREHOUSE ONTO_WH TO ROLE ONTO_LOGISTICS;
GRANT USAGE ON WAREHOUSE ONTO_WH TO ROLE ONTO_JUDGE;

-- Database & Schema Grants
GRANT USAGE ON DATABASE ONTO_HACKATHON TO ROLE ONTO_PLANNER;
GRANT USAGE ON DATABASE ONTO_HACKATHON TO ROLE ONTO_PROCUREMENT;
GRANT USAGE ON DATABASE ONTO_HACKATHON TO ROLE ONTO_LOGISTICS;
GRANT USAGE ON DATABASE ONTO_HACKATHON TO ROLE ONTO_JUDGE;

GRANT USAGE ON SCHEMA ONTO_HACKATHON.CORE TO ROLE ONTO_PLANNER;
GRANT USAGE ON SCHEMA ONTO_HACKATHON.CORE TO ROLE ONTO_PROCUREMENT;
GRANT USAGE ON SCHEMA ONTO_HACKATHON.CORE TO ROLE ONTO_LOGISTICS;
GRANT USAGE ON SCHEMA ONTO_HACKATHON.CORE TO ROLE ONTO_JUDGE;

GRANT USAGE ON SCHEMA ONTO_HACKATHON.MART TO ROLE ONTO_PLANNER;
GRANT USAGE ON SCHEMA ONTO_HACKATHON.MART TO ROLE ONTO_PROCUREMENT;
GRANT USAGE ON SCHEMA ONTO_HACKATHON.MART TO ROLE ONTO_LOGISTICS;
GRANT USAGE ON SCHEMA ONTO_HACKATHON.MART TO ROLE ONTO_JUDGE;

-- 2. DYNAMIC DATA MASKING POLICY
-- Sensitive procurement pricing & freight expenses masked for non-authorized personas
CREATE OR REPLACE MASKING POLICY GOV.MASK_COST_DATA AS (val FLOAT) RETURNS FLOAT ->
    CASE 
        WHEN CURRENT_ROLE() IN ('ONTO_PROCUREMENT', 'ONTO_JUDGE', 'ACCOUNTADMIN') THEN val
        ELSE NULL -- Masked out for Logistics & Planner
    END;

-- Apply Masking Policy to Base Tables
ALTER TABLE ONTO_HACKATHON.CORE.CORE_PART MODIFY COLUMN unit_cost SET MASKING POLICY GOV.MASK_COST_DATA;
ALTER TABLE ONTO_HACKATHON.CORE.CORE_SHIPMENT MODIFY COLUMN freight_cost SET MASKING POLICY GOV.MASK_COST_DATA;

-- 3. ROW ACCESS POLICIES (RAP)
-- Base tables are entitled; MART_OTD_AGGREGATE is RAP-unrestricted!
CREATE OR REPLACE ROW ACCESS POLICY GOV.RAP_ORDER_LINE AS (plant_id VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ONTO_PLANNER', 'ONTO_JUDGE', 'ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() = 'ONTO_PROCUREMENT' THEN TRUE
        WHEN CURRENT_ROLE() = 'ONTO_LOGISTICS' AND plant_id IN ('P01', 'P03', 'P07', 'P09') THEN TRUE
        ELSE FALSE
    END;

ALTER TABLE ONTO_HACKATHON.CORE.CORE_ORDER_LINE ADD ROW ACCESS POLICY GOV.RAP_ORDER_LINE ON (plant_id);

-- 4. PERMISSION GRANTS
-- All roles have SELECT on the certified RAP-unrestricted MART_OTD_AGGREGATE
GRANT SELECT ON TABLE ONTO_HACKATHON.MART.MART_OTD_AGGREGATE TO ROLE ONTO_PLANNER;
GRANT SELECT ON TABLE ONTO_HACKATHON.MART.MART_OTD_AGGREGATE TO ROLE ONTO_PROCUREMENT;
GRANT SELECT ON TABLE ONTO_HACKATHON.MART.MART_OTD_AGGREGATE TO ROLE ONTO_LOGISTICS;
GRANT SELECT ON TABLE ONTO_HACKATHON.MART.MART_OTD_AGGREGATE TO ROLE ONTO_JUDGE;

-- Granular tables granted
GRANT SELECT ON ALL TABLES IN SCHEMA ONTO_HACKATHON.CORE TO ROLE ONTO_PLANNER;
GRANT SELECT ON ALL TABLES IN SCHEMA ONTO_HACKATHON.CORE TO ROLE ONTO_PROCUREMENT;
GRANT SELECT ON ALL TABLES IN SCHEMA ONTO_HACKATHON.CORE TO ROLE ONTO_LOGISTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA ONTO_HACKATHON.CORE TO ROLE ONTO_JUDGE;

-- 5. AUDIT LOGGING TABLE
-- Powers the Trust Panel and records compliance across personas
CREATE OR REPLACE TABLE ONTO_HACKATHON.GOV.AUDIT_LOG (
    log_id                          VARCHAR(64) DEFAULT UUID_STRING() PRIMARY KEY,
    execution_timestamp            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    user_name                       VARCHAR(128) DEFAULT CURRENT_USER(),
    persona_role                    VARCHAR(64) DEFAULT CURRENT_ROLE(),
    nl_question                     TEXT,
    generated_sql                   TEXT,
    metric_contract_id              VARCHAR(32),
    rows_scanned                    NUMBER,
    entitlement_policy_applied      VARCHAR(128),
    semantic_grounding_status       VARCHAR(32) DEFAULT 'GROUNDED_SEMANTIC_SPEC',
    is_refused                      BOOLEAN DEFAULT FALSE,
    refusal_reason                  TEXT
);

-- Audit table grants
GRANT INSERT, SELECT ON TABLE ONTO_HACKATHON.GOV.AUDIT_LOG TO ROLE ONTO_PLANNER;
GRANT INSERT, SELECT ON TABLE ONTO_HACKATHON.GOV.AUDIT_LOG TO ROLE ONTO_PROCUREMENT;
GRANT INSERT, SELECT ON TABLE ONTO_HACKATHON.GOV.AUDIT_LOG TO ROLE ONTO_LOGISTICS;
GRANT INSERT, SELECT ON TABLE ONTO_HACKATHON.GOV.AUDIT_LOG TO ROLE ONTO_JUDGE;
